[tool.black]
line-length = 88

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I", "B"]
ignore = []

[tool.pytest.ini_options]
addopts = "-q"
pythonpath = [
    "."
]
asyncio_mode = "auto"
